# Note that the following stanza uses CircleCI 2.1 to make use of a Reusable Executor
# This allows defining a docker image to reuse across jobs.
# visit https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors to learn more.

version: 2.1
orbs:
  portshiftscanner: 'moriya/scanner-orb@0.0.37'
jobs:
  docker-build:
    machine: true
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: 'docker pull mongo:latest'
      - run: 'docker save -o workspace/mongo.tar mongo:latest'
      - persist_to_workspace:
          root: workspace
          paths:
            - mongo.tar
workflows:
  scan-image:
    jobs:
      - docker-build
      - portshiftscanner/scan-image:
          requires:
            - docker-build
          context: blabla
          image_name: 'registry.gitlab.com/portshift/portshift/vault'
          image_tag: '0.10.1'
          highest_severity_allowed: 'LOW'